name: Create and publish a Docker iamge

on:
  push:
    branches:
      - "main"

jobs:
  # buildpaddle:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check Out Repo
  #       uses: actions/checkout@v3

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKER_HUB_USERNAME }}
  #         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  #     - name: Set up Docker Buildx
  #       id: buildx
  #       uses: docker/setup-buildx-action@v2

  #     - name: Build and push
  #       id: docker_build
  #       uses: docker/build-push-action@v4
  #       with:
  #         context: ./
  #         file: ./Dockerfilepaddle
  #         push: true
  #         tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pytorch-notebook:paddle

  #     - name: Image digest
  #       run: echo ${{ steps.docker_build.outputs.digest }}
  #  buildbase:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Check Out Repo
  #        uses: actions/checkout@v3
  #
  #      - name: Login to Docker Hub
  #        uses: docker/login-action@v2
  #        with:
  #          username: ${{ secrets.DOCKER_HUB_USERNAME }}
  #          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  #
  #      - name: Set up Docker Buildx
  #        id: buildx
  #        uses: docker/setup-buildx-action@v2
  #
  #      - name: Build and push
  #        id: docker_build
  #        uses: docker/build-push-action@v4
  #        with:
  #          context: ./
  #          file: ./Dockerfile
  #          push: true
  #          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pytorch-notebook:base
  #
  #      - name: Image digest
  #        run: echo ${{ steps.docker_build.outputs.digest }}

  #  build11:
  #    runs-on: ubuntu-latest
  #    steps:
  #
  #      - name: Check Out Repo
  #        uses: actions/checkout@v3
  #
  #      - name: Login to Docker Hub
  #        uses: docker/login-action@v2
  #        with:
  #          username: ${{ secrets.DOCKER_HUB_USERNAME }}
  #          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  #
  #      - name: Set up Docker Buildx
  #        id: buildx
  #        uses: docker/setup-buildx-action@v2
  #
  #      - name: Build and push
  #        id: docker_build
  #        uses: docker/build-push-action@v4
  #        with:
  #          context: ./
  #          file: ./Dockerfile
  #          push: true
  #          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pytorch-notebook:11.7
  #
  #      - name: Image digest
  #        run: echo ${{ steps.docker_build.outputs.digest }}

   # build12:
   #   runs-on: ubuntu-latest
   #   steps:
  
   #     - name: Check Out Repo
   #       uses: actions/checkout@v3
  
   #     - name: Login to Docker Hub
   #       uses: docker/login-action@v2
   #       with:
   #         username: ${{ secrets.DOCKER_HUB_USERNAME }}
   #         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  
   #     - name: Set up Docker Buildx
   #       id: buildx
   #       uses: docker/setup-buildx-action@v2
  
   #     - name: Build and push
   #       id: docker_build
   #       uses: docker/build-push-action@v4
   #       with:
   #         context: ./
   #         file: ./Dockerfile12
   #         push: true
   #         tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pytorch-notebook:12.0
  
   #     - name: Image digest
   #       run: echo ${{ steps.docker_build.outputs.digest }}
  build121:
    runs-on: ubuntu-latest
    steps:

      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile12.1
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pytorch-notebook:12.1

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

#  buildyolo:
#    runs-on: ubuntu-latest
#    steps:
#
#      - name: Check Out Repo
#        uses: actions/checkout@v3
#
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#
#      - name: Set up Docker Buildx
#        id: buildx
#        uses: docker/setup-buildx-action@v2
#
#      - name: Build and push
#        id: docker_build
#        uses: docker/build-push-action@v4
#        with:
#          context: ./
#          file: ./Dockerfileyolo
#          push: true
#          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pytorch-notebook:yolo
#
#      - name: Image digest
#        run: echo ${{ steps.docker_build.outputs.digest }}
